config/routes.rb
Daitss::Application.routes.draw do
  get "packages/new"
  get "packages/submit"

  resources :accounts
  resources :projects
  resources :users
  resources :packages, only: [:index, :submit]
  resources :sessions, only: [:new, :create, :destroy]
  resource :workspace, :controller => :workspace, except: [:show]
  resource :stashspace, :controller => :stashspace, except: [:show]
  resources :operators, :controller => "users" # single table inheritance, operator is a kind of user.
  resources :contacts, :controller => "users" # single table inheritance, contact is a kind of user.

  root to: 'sessions#new'
  match '/dashboard', to: 'main#dashboard'
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete    
  match '/help',  to: 'main#help'
  match '/admin' => 'main#admin'
  match '/log', to: 'main#log'
  match '/log_message', to: 'main#log_message'  
  match '/edit_password', to: 'users#edit_password'  
  match '/update_password', to: 'users#update_password'  
  match '/submit', to: 'packages#submit'
  match '/upload', to: 'packages#upload'
  match '/submit_request', to: 'packages#submit_request'
  match '/workspace', to: 'workspace#workspace'
  match '/update', to: 'workspace#update'
  match '/stashspace', to: 'stashspace#stashspace'
  match '/stashspace/:id', to: 'stashspace#delete'
  
  get '/packages/:id', to: 'packages#show', :as => 'package'
  get '/workspace/:id', to: 'workspace#show', :as => 'wip'
  get 'main/select_account', :as => 'select_account'
  get 'packages/select_package_account', :as => 'select_package_account'
  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:index, :edit, :update, :destroy] #only signed in user can edit/update/list
  before_filter :correct_user,   only: [:edit, :update] # make sure an user can only edit his/her own information

  # retrieve selected permissions
  def getPermissions
    perms = []
    perms.push :disseminate if params[:disseminate_perm] == "on"
    perms.push :withdraw if params[:withdraw_perm] == "on"
    perms.push :peek if params[:peek_perm] == "on"
    perms.push :submit if params[:submit_perm] == "on"
    perms.push :report if params[:report_perm] == "on"      
    perms    
  end

  def index
    # @users = User.all
    @users = User.paginate(page: params[:page])
  end

  # retrieve the information for the selected user (agent)
  def show
    @user = User.get(params[:id])    
  end

  def new
    @user = User.new
  end

  # create a new user model with the information entered.
  def create
    if params[:type] == "operator"
      @user = Operator.new(params[:user])
      @user.account = Account.get("SYSTEM")
    else
      account_id = params[:user][:account_id]
      a = Account.get account_id   
      @user = Contact.new (params[:user])
      @user.account = a
      @user.permissions = getPermissions
      # setup role
      @user.is_admin_contact = true if params[:is_admin_contact] == 'yes'
      @user.is_tech_contact = true if params[:is_tech_contact] == 'yes'
    end
    
    @user.encrypt_auth(@user.auth_key)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Florida Digital Archive!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.get(params[:id])
  end

  # update user profile
  def update
    @user = User.get(params[:id])
    #    if @user.authenticate(params[:user][:auth_key]) && @user.update(params[:user])

    # get the selected permissions
    if (@user.type == Contact)
      perms = getPermissions
      params[:user].merge!("permission" => perms)
    end
    
    if @user.update(params[:user])
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end

  def edit_password
  @user = User.get(params[:id])
  end
  
  def update_password
    @user = User.get(params[:id])
    if params[:Password] != params[:Confirm_Password]
     flash[:danger] = "Password not matched"
     render 'edit_password'
    else
      @user.encrypt_auth params[:Password]
      @user.save or flash[:danger] = "cannot save #{user.id} password, #{user.errors.full_messages}"
      flash[:success] = "Password updated"
      render 'edit'
    end    
  end
  
  # update user profile by an administrator
  def admin_update
    @user = User.get(params[:id])
    if @user.update(params[:user])
      flash[:success] = "User updated"
    else
      render 'edit'
    end
  end  

  def destroy
    User.get(params[:id]).destroy!
    flash[:success] = "User destroyed."
    redirect_to users_url
  end

  private
  # sign in the user, and store their original url location.
  def signed_in_user
    store_location
    redirect_to signin_url, notice: "Please sign in." unless signed_in?
  end

  def correct_user
    @user = User.get(params[:id])
    redirect_to(root_path) unless current_user?(@user)
  end  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/admin_edit.erb
<% provide(:title, 'Edit User by an Administrator') %>
<h1>Update User</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
    <%#= render 'shared/error_messages' %>
    <%= f.label :id %>
    <%= f.text_field :id %>

    <%= f.label :description %>
    <%= f.text_field :description %>

    <%= f.label :account_id %>
    <%= f.select(:account_id, Account.all.collect {|a| a.id}) %>

    <%= f.label :first_name %>
    <%= f.text_field :first_name %>

    <%= f.label :last_name %>
    <%= f.text_field :last_name %>

    <%= f.label :email %>
    <%= f.text_field :email %>

    <%= f.label :phone %>
    <%= f.text_field :phone %>

    <%= f.label :address %>
    <%= f.text_field :address %>

    <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<% provide(:title, 'Edit User') %>
<h1>Update your profile</h1>
<div class="col-md-9 col-md-offset-3">
  <% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
</div>
<%= form_for(@user, :as => :user, :html => {:class => "form-horizontal"}) do |f| %>
<div class="form-group">
  <%= f.label :id, :class=>"col-md-2 col-md-offset-1 control-label" %>
  <div class="col-md-2">
    <%= f.text_field :id,  :class=>"form-control", :readonly => true %>
  </div>
  <%= f.label :description, :class=>"col-md-2 control-label"  %>
  <div class=" col-md-3 ">
    <%= f.text_field :description, :class=>"form-control" %>
  </div>  
</div>

<div class="form-group">
  <%= f.label :type, :class=>"col-md-2 col-md-offset-1 control-label " %>
  <div class="col-md-2">    
    <%= select_tag(:type, options_for_select([['operator', 'operator'], ['affiliates', 'affiliates']]), disabled:true )%>
  </div>

  <%= f.label :account_id, :class=>"col-md-2 control-label"  %>
  <div class="col-md-3 ">
    <%= f.select(:account_id, Account.all.collect {|a| a.id}) %>
  </div>  
</div>

<div class="form-group">
  <%= f.label :first_name, :class=>"col-md-2 col-md-offset-1 control-label"  %>
  <div class="col-md-2">
    <%= f.text_field :first_name, :class=>"form-control" %>
  </div>
  <%= f.label :last_name,:class=>"col-md-2 control-label" %>
  <div class="col-md-3 ">
    <%= f.text_field :last_name, :class=>"form-control" %>
  </div>
</div>

<div class="form-group">
  <%= f.label :phone, :class=>"col-md-2 col-md-offset-1 control-label"  %>
  <div class="col-md-2 ">
    <%= f.text_field :phone, :class=>"form-control" %>
  </div>
  <%= f.label :email, :class=>"col-md-2 control-label"  %>
  <div class="col-md-3 ">
    <%= f.text_field :email, :class=>"form-control", :type => "email" %>
  </div>  
</div>

<div class="form-group">
  <div class="col-md-2 col-md-offset-3">
    <%= link_to "Edit Password", edit_password_path(:id => @user.id) %>
  </div>   
  <%= f.label :address, :class=>"col-md-2 control-label"  %>
  <div class="col-md-3">
    <%= f.text_area :address, :class=>"form-control", rows: "2" %>
  </div> 
</div>

<div class="form-group">
  <div class="col-md-2 col-md-offset-3">
    <%= f.check_box :is_admin_contact, :class=>"check-box", :value=>"yes"%>    
    <%= f.label :Admin_Contact%>
  </div>
  <div class="col-md-3 col-md-offset-2">
    <%= f.check_box :is_tech_contact, :class=>"check-box", :value=>"yes"%>    
    <%= f.label :Tech_Contact%>    
  </div>
</div>

<% if :type == Contact  %> 
<div class="form-group ">
  <%= f.label :permissions, :class=>"col-md-2 control-label col-md-offset-1 "  %>
  <div class="col-md-7">
    <label class="checkbox-inline" class="check-box">
      <input type="checkbox" name="disseminate_perm" class="check-box" value="on"> Disseminate
    </label>
    <label class="checkbox-inline" class="check-box" >
      <input type="checkbox" name="withdraw_perm" class="check-box" value="on"> Withdraw
    </label>
    <label class="checkbox-inline" class="check-box" >
      <input type="checkbox" name="peek_perm" class="check-box" value="on"> Peek
    </label>  
    <label class="checkbox-inline" class="check-box" >
      <input type="checkbox" name="submit_perm" class="check-box" value="on"> Submit
    </label>
    <label class="checkbox-inline" class="check-box" >
      <input type="checkbox" name="report_perm" class="check-box" value="on"> Report
    </label>
  </div>
</div>
<%end%>
<div class="form-group">
  <div class="col-md-2 col-md-offset-5">
    <%= f.submit "Save", class: "btn btn-lg btn-primary" %>
  </div>
</div>
<% end %>

app/views/users/edit_password.html.erb
<% provide(:title, 'Edit User') %>
<h1>Update your password</h1>
<div class="row">
  <% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user updating password:</h2>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <div class="col-md-3 col-md-offset-4">
    
    <form action="update_password" method ="post" enctype="multipart/form-data">
    <%= label_tag 'Password' %>
    <%= text_field_tag 'Password' %>
    <%= label_tag 'Confirm Password' %>
    <%= text_field_tag 'Confirm_Password' %>  
    <input name="id" type="hidden" value="<%= @user.id %>" />
    <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" />
    <%= submit_tag "Save", :class=>"btn", :name => nil %>
    </form>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All Users') %>
<h6>Admin->Users</h6>

<div class="row">
  <div class="col-md-2 col-md-offset-10">
    <%= link_to 'New User', new_user_path %>
  </div>
</div>

<%= will_paginate %>

<table class="table table-striped">
  <tr>
    <th>Id</th>
    <th>Account</th>
    <th>Description</th>
    <th>Emails</th>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Tech Contact</th>   
    <th>Admin Contact</th>        
    <th></th>
  </tr>

  <% @users.each do |user| %>
  <tr>
    <td><%= link_to user.id, user %></td>
    <td><%= user.account_id %></td>
    <td><%= user.description %></td>
    <td><%= user.email %></td>
    <td><%= user.first_name %></td>
    <td><%= user.last_name %></td>
    <td><%= check_box_tag 'tech_contact', user.is_tech_contact, user.is_tech_contact %></td>    
    <td><%= check_box_tag 'admin_contact', user.is_admin_contact, user.is_admin_contact %></td>
    <% if admin_user? %>
      <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <% end %>
    <% if admin_user? && !current_user?(user) %>
      <td><%= link_to "Delete", user, method: :delete, data: { confirm: "You sure?" } %></td>
    <% end %>
  </tr>
  <% end %>
</table>
<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<div class="col-md-9 col-md-offset-3">
  <% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
</div>
<%= form_for(@user, :as => :user, :html => {:class => "form-horizontal"}) do |f| %>
<div class="form-group">
  <%= f.label :id, :class=>"col-md-2 col-md-offset-1 control-label" %>
  <div class="col-md-2">
    <%= f.text_field :id,  :class=>"form-control" %>
  </div>
  <%= f.label :description, :class=>"col-md-2 control-label"  %>
  <div class=" col-md-3 ">
    <%= f.text_field :description, :class=>"form-control" %>
  </div>  
</div>

<div class="form-group">
  <%= f.label :type, :class=>"col-md-2 col-md-offset-1 control-label " %>
  <div class="col-md-2">    
    <%= select_tag(:type, options_for_select([['operator', 'operator'], ['affiliates', 'affiliates']]) )%>
  </div>

  <%= f.label :account_id, :class=>"col-md-2 control-label"  %>
  <div class="col-md-3 ">
    <%= f.select(:account_id, Account.all.collect {|a| a.id}) %>
  </div>  
</div>

<div class="form-group">

 
</div>

<div class="form-group">
  <%= f.label :first_name, :class=>"col-md-2 col-md-offset-1 control-label"  %>
  <div class="col-md-2">
    <%= f.text_field :first_name, :class=>"form-control" %>
  </div>
  <%= f.label :last_name,:class=>"col-md-2 control-label" %>
  <div class="col-md-3 ">
    <%= f.text_field :last_name, :class=>"form-control" %>
  </div>
</div>

<div class="form-group">
  <%= f.label :phone, :class=>"col-md-2 col-md-offset-1 control-label"  %>
  <div class="col-md-2 ">
    <%= f.text_field :phone, :class=>"form-control" %>
  </div>
  <%= f.label :email, :class=>"col-md-2 control-label"  %>
  <div class="col-md-3 ">
    <%= f.text_field :email, :class=>"form-control", :type => "email" %>
  </div>  
</div>

<div class="form-group">
  <%= f.label :password, :class=>"col-md-2 col-md-offset-1 control-label"  %>
  <div class="col-md-2">  
    <%= f.password_field :auth_key, :placeholder => "Password" %>
  </div>
  <%= f.label :address, :class=>"col-md-2 control-label"  %>
  <div class="col-md-3">
    <%= f.text_area :address, :class=>"form-control", rows: "2" %>
  </div> 
</div>

<div class="form-group">
  <div class="col-md-2 col-md-offset-3">
    <%= f.check_box :is_admin_contact, :class=>"check-box", :value=>"yes"%>    
    <%= f.label :Admin_Contact%>
  </div>
  <div class="col-md-3 col-md-offset-2">
    <%= f.check_box :is_tech_contact, :class=>"check-box", :value=>"yes"%>    
    <%= f.label :Tech_Contact%>    
  </div>
</div>
  
<div class="form-group ">
  <%= f.label :permissions, :class=>"col-md-2 control-label col-md-offset-1 "  %>
  <div class="col-md-7">
    <label class="checkbox-inline" class="check-box">
      <input type="checkbox" name="disseminate_perm" class="check-box" value="on"> Disseminate
    </label>
    <label class="checkbox-inline" class="check-box" >
      <input type="checkbox" name="withdraw_perm" class="check-box" value="on"> Withdraw
    </label>
    <label class="checkbox-inline" class="check-box" >
      <input type="checkbox" name="peek_perm" class="check-box" value="on"> Peek
    </label>  
    <label class="checkbox-inline" class="check-box" >
      <input type="checkbox" name="submit_perm" class="check-box" value="on"> Submit
    </label>
    <label class="checkbox-inline" class="check-box" >
      <input type="checkbox" name="report_perm" class="check-box" value="on"> Report
    </label>
  </div>
</div>
<div class="form-group">
  <div class="col-md-2 col-md-offset-5">
    <%= f.submit "Save", class: "btn btn-lg btn-primary" %>
  </div>
</div>
<% end %>

app/views/users/show.html.erb
<% provide(:title, @user.id) %>
<h1><%= @user.id %></h1>
<h3><%= @user.description %></h3>
<h3><%= @user.account_id %></h3>
<h3><%= @user.first_name %></h3>
<h3><%= @user.last_name%></h3>
<h3><%= @user.email %></h3>
<h3><%= @user.address %></h3>
<h3><%= @user.phone %></h3>