config/routes.rb
Daitss::Application.routes.draw do
  get "packages/new"
  get "packages/submit"

  resources :accounts
  resources :projects
  resources :users
  resources :packages, only: [:index, :submit]
  resources :sessions, only: [:new, :create, :destroy]
  resource :workspace, :controller => :workspace, except: [:show]
  resource :stashspace, :controller => :stashspace, except: [:show]
  resources :operators, :controller => "users" # single table inheritance, operator is a kind of user.
  resources :contacts, :controller => "users" # single table inheritance, contact is a kind of user.

  root to: 'sessions#new'
  match '/dashboard', to: 'main#dashboard'
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete    
  match '/help',  to: 'main#help'
  match '/admin' => 'main#admin'
  match '/log', to: 'main#log'
  match '/log_message', to: 'main#log_message'  
  match '/edit_password', to: 'users#edit_password'  
  match '/update_password', to: 'users#update_password'  
  match '/submit', to: 'packages#submit'
  match '/upload', to: 'packages#upload'
  match '/submit_request', to: 'packages#submit_request'
  match '/workspace', to: 'workspace#workspace'
  match '/update', to: 'workspace#update'
  match '/stashspace', to: 'stashspace#stashspace'
  match '/stashspace/:id', to: 'stashspace#delete'
  
  get '/packages/:id', to: 'packages#show', :as => 'package'
  get '/workspace/:id', to: 'workspace#show', :as => 'wip'
  get 'main/select_account', :as => 'select_account'
  get 'packages/select_package_account', :as => 'select_package_account'
  

end

app/models/project.rb
class Project
  include DataMapper::Resource

  property :id, String, :key => true
  property :description, Text

  property :account_id, String, :key => true

  has 0..n, :packages

  belongs_to :account, :key => true
  
 def to_param
    id
   # "#{id}/#{account_id}"
  end
  
  # retrieve the list of user accounts, excluding the "SYSTEM" - system account used by DAITSS program
  def self.user_projects
    Project.all - Project.all(:account_id => "SYSTEM")
  end    
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  before_filter :authenticate_admin

  def index
    @projects = Project.user_projects
  end
    
  def new
    @project = Project.new
  end
  
  # create a new project model with the information entered.
  def create
    @project = Project.new(params[:project])
      
    if @project.save
      flash[:success] = "Project created"      
      redirect_to projects_url
    else
      flash[:danger] = "Cannot create project"
      render 'new'
    end
  end
 
  def edit
    @project = Project.get(params[:id], params[:account_id])
  end  

  # update project
  def update   
    @project = Project.get(params[:id], params[:account_id])
    begin
      @project.update(params[:project])
      flash[:success] = "Project updated"
      redirect_to projects_url  
    rescue => e
      flash[:danger] = "Cannot update project, other packages still reference it"
      redirect_to projects_url        
    end
  end  

  def destroy
    if (Project.get(params[:id], params[:account_id]).destroy)
      flash[:success] = "Project destroyed."
      redirect_to projects_url
    else
      flash[:danger] = "Cannot delete project, other packages still reference it"
      redirect_to projects_url      
    end
  end
      
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">  
    <% unless @project.errors.blank? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
        <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <div class="field">
      <%= f.label :id %><br />
      <%= f.text_field :id %>
    </div>
    <div class="field">
      <%= f.label :description %><br />
      <%= f.text_field :description %>
    </div>
    <div class="field">
      <%= f.label :account_id %><br />
      <%= f.select(:account_id, Account.user_accounts.collect {|a| a.id}) %>
      <%= hidden_field_tag :account_id, @project.account_id%> 
      <div class="actions">
        <%= f.submit %>
      </div>
    </div>
  </div> 
</div>
<% end %>

app/views/projects/edit.html.erb
<% provide(:title, 'Edit project') %>
<h6>Admin->project->Edit</h6>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<% provide(:title, 'All Projects') %>
<h6>Admin->Projects</h6>
<div class="row">
  <div class="col-md-2 col-md-offset-10">
    <%= link_to 'New Project', new_project_path %>
  </div>
</div>
<table class='table table-striped'>
  <tr>
    <th>Id</th>
    <th>Description</th>
    <th>Account</th>
    <th></th>
    <th></th>
  </tr>

  <% @projects.each do |project| %>
  <tr>
    <td><%= project.id %></td>
    <td><%= project.description %></td>
    <td><%= project.account_id%></td>
    <td><%= link_to 'Edit', edit_project_path(:id => project.id, :account_id => project.account_id) %></td>
    <td><%= link_to 'Delete', project_path(project, :account_id => project.account_id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
  <% end %>
</table>

app/views/projects/new.html.erb
<% provide(:title, 'New Project') %>
<h6>Admin->Project->New</h6>
<%= render 'form' %>

<%= link_to 'Back', projects_path %>