config/routes.rb
Daitss::Application.routes.draw do
  get "packages/new"
  get "packages/submit"

  resources :accounts
  resources :projects
  resources :users
  resources :packages, only: [:index, :submit]
  resources :sessions, only: [:new, :create, :destroy]
  resource :workspace, :controller => :workspace, except: [:show]
  resource :stashspace, :controller => :stashspace, except: [:show]
  resources :operators, :controller => "users" # single table inheritance, operator is a kind of user.
  resources :contacts, :controller => "users" # single table inheritance, contact is a kind of user.

  root to: 'sessions#new'
  match '/dashboard', to: 'main#dashboard'
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete    
  match '/help',  to: 'main#help'
  match '/admin' => 'main#admin'
  match '/log', to: 'main#log'
  match '/log_message', to: 'main#log_message'  
  match '/edit_password', to: 'users#edit_password'  
  match '/update_password', to: 'users#update_password'  
  match '/submit', to: 'packages#submit'
  match '/upload', to: 'packages#upload'
  match '/submit_request', to: 'packages#submit_request'
  match '/workspace', to: 'workspace#workspace'
  match '/update', to: 'workspace#update'
  match '/stashspace', to: 'stashspace#stashspace'
  match '/stashspace/:id', to: 'stashspace#delete'
  
  get '/packages/:id', to: 'packages#show', :as => 'package'
  get '/workspace/:id', to: 'workspace#show', :as => 'wip'
  get 'main/select_account', :as => 'select_account'
  get 'packages/select_package_account', :as => 'select_package_account'
  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="https://github.com/cchou/daitss">DAITSS github</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   'http://fclaweb.fcla.edu/FDA' %></li>
      <li><%= link_to "Help",    help_path %></li>      
      <li><%= link_to "Contact", 'http://www.flvc.org/flvc/portal/Home_Page/About%20FLVC/Contact_Us/!ut/p/c5/04_SB8K8xLLM9MSSzPy8xBz9CP0os3hDYxNPf293QwN_Q1MjA09jV3dLswBXIwsnQ30_j_zcVP2CbEdFAA4MQCA!/dl3/d3/L2dJQSEvUUt3QS9ZQnZ3LzZfMTM0SU9LRzEwTzE1MjBJM0VHOTZQRTI4TjE!/' %></li>
      <li><a href="http://daitss.fcla.edu">Open Source</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<div class="visible-xs">
  <%= link_to image_tag("FLVC_logo_symbol_medium.png", alt: "FLVC"), 'http://www.flvc.org' %>
</div>
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="col-md-2 pull-left hidden-xs">
      <%= link_to image_tag("FLVC_logo_symbol_medium.png", alt: "FLVC"), 'http://www.flvc.org' %>
    </div>
    <div class="col-md-9">
      <ul class="nav navbar-nav navbar-right">
        <% if signed_in? %>
        <li><%= link_to "Home", dashboard_path %></li>
        <% if current_user.is_admin_contact? || current_user.class == Operator%>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Admin <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "View", admin_path %></li>
            <li><%= link_to "Work Space", workspace_path %></li>
            <li><%= link_to "Stash Space", stashspace_path %></li>
            <li><%= link_to "Accounts", accounts_path %></li>
            <li><%= link_to "Projects", projects_path %></li>
            <li><%= link_to "Users", users_path %></li>
            <li><%= link_to "Log", log_path %></li>
          </ul>
        </li>
        <% end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Packages <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Submit", submit_path %></li>
            <li><%= link_to "View", packages_path %></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            User <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Profile", current_user %></li>
            <li><%= link_to "Settings", edit_user_path(current_user) %></li>
            <li class="divider"></li>
            <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
          </ul>
        </li>
        <% else %>
        <li><%= link_to "Sign in", signin_path %></li>
        <% end %>
      </ul>
    </div> 
    <div class="col-md-1 visible-lg visible-md">
      <%= link_to image_tag("FDA-colorLogo.png", alt: "FDA"), 'http://fclaweb.fcla.edu/FDA' %>
    </div>      
  </div>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<meta name="viewport" content="width=device-width, initial-scale=1">
<head>
  <title>Florida Digital Archive | <%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application", "packages" %> 
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>   
</head>
<body>
  <%=render 'layouts/header' %>
  <div class="container">
    <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>